spring:
  datasource:
    url: jdbc:h2:mem:stockorderservicedb;MODE=LEGACY
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    locations: classpath:db/migration/h2
